uploads = []
generated = []

[[outputs]]
id = "Sh9q9NC7JUVO7Pq_B0gA4"
uri = "file://docs/TECHNICAL_DOCUMENTATION.md"
type = "text"
title = "Technical Documentation"

[[outputs]]
id = "U_QZ-URt6V8mAhgwX-h4v"
uri = "file://docs/USER_MANUAL.md"
type = "text"
title = "User Manual (Bahasa Indonesia)"
